footnotes_blocklist <- block_list(fpar(ftext("Melia P et al. Development of the INFERENCE (INtegration of Forensic Epidemiology and the Rigorous EvaluatioN of Causation Elements) approach to causal inference in forensic medicine. Int J Environ Res Public Health 2020;17:8353; doi:10.3390/ijerph17228353."), fp_p = fp_par_footnote), 
  fpar(ftext("Freeman MD. A practicable and systematic approach to medicolegal causation. Orthopedics 2018;41(2):70-2."), fp_p = fp_par_footnote),
  fpar(ftext("Freeman MD, Centeno CJ, Kohles SS. A systematic approach to clinical determinations of causation in symptomatic spinal disc injury following motor vehicle crash trauma. PM R 2009;1(10):951-6."), fp_p = fp_par_footnote),
  fpar(ftext("Etherton v. Owner Insurance Company. U.S. District Court of Appeals, 10th Circuit. Case No. 14-1164."), fp_p = fp_par_footnote),
  fpar(ftext("Freeman MD, Zeegers M. Principles and applications of forensic epidemiology in the medicolegal setting. Law, Probability, & Risk 2015; doi:10.1093/lpr/mgv010."), fp_p = fp_par_footnote),
  fpar(ftext("Koehler S, Freeman MD. Forensic epidemiology; a methodology for investigating and quantifying specific causation. Forens Sci Med Path 2014 Jun;10(2):217-22"), fp_p = fp_par_footnote),
  fpar(ftext("Hashish R, Badday H. Frequency of acute cervical and lumbar pathology in common types of motor vehicle collisions: a retrospective record review. BMC Musculoskeletal Disorders 2017;18:437"), fp_p = fp_par_footnote),
  fpar(ftext("Bunketorp O (2017) WAD – Criteria for Evaluation of Causality. Open J Trauma 1(3):054-063."), fp_p = fp_par_footnote),
  fpar(ftext("35 F.Supp.3d 1360 United States District Court, D. Colorado. Donald L. Etherton, Plaintiff, v. Owners Insurance Company, a Michigan Insurance Company, Defendant. Civil Action No. 10–cv–00892– PAB–KLM"), fp_p = fp_par_footnote),
  fpar(ftext("Wang, J.-S. (2022, May). MAIS(05/08) injury probability curves as functions of delta V (Report No. DOT HS 813 219). National Highway Traffic Safety Administration."), fp_p = fp_par_footnote),
  fpar(ftext("Nolet et al. Is acceleration a valid proxy for injury risk in minimal damage traffic crashes? A comparative review of volunteer, ADL and real-world studies. Int J Environ Res Public Health 2021;18:2901; https://doi.org/10.3390/ijerph18062901."), fp_p = fp_par_footnote),
  fpar(ftext(paste0("Based on ", Mr_Ms_Lastname(), "’s weight of ", plaintiff$weight, ", lbs. at the time of the crash, and the standard assumption that approximately 60% of ", his_her(), " weight is in ", his_her(), " trunk (above the waist).")), fp_p = fp_par_footnote),
  fpar(ftext("Freeman MD, Leith WM. Estimating the number of traffic crash-related cervical spine injuries in the United States; an analysis and comparison of national crash and hospital data. Accident Analysis and Prevention 2020: doi:https://doi.org/10.1016/j.aap.2020.105571."), fp_p = fp_par_footnote),
  fpar(ftext("Fardon et al. Lumbar disc nomenclature: version 2.0: Recommendations of the combined task forces of the North American Spine Society, the American Society of Spine Radiology and the American Society of Neuroradiology. Spine J. 2014;14(11):2525-45."), fp_p = fp_par_footnote),
  fpar(ftext("Giuliano et al. The use of flexion and extension MR in the evaluation of cervical spine trauma: initial experience in 100 trauma patients compared with 100 normal subjects. Emerg Radiol. 2002;9(5):249-53."), fp_p = fp_par_footnote),
  fpar(ftext("Freeman et al. Significant spinal injury resulting from low-level accelerations: A case series of roller coaster injuries. Arch Phys Med Rehab 2005;86:2126-30."), fp_p = fp_par_footnote),
  fpar(ftext("Lutz et al. CT myelography of a fragment of a lumbar disk sequestered posterior to the thecal sac. Am J Neuroradiol 1990;11(3):610-1."), fp_p = fp_par_footnote),
  fpar(ftext("Sadanand et al. Sudden quadriplegia after acute cervical disc herniation. Can J Neurol Sci 2005;32(3):356-8."), fp_p = fp_par_footnote),
  fpar(ftext("Pappas et al. Outcome analysis in 654 surgically treated lumbar disc herniations. Neurosurgery 1992;30(6):862–6."), fp_p = fp_par_footnote),
  fpar(ftext("Smith J. An analysis of 72 real world impacts - an initial investigation into injury and complaint factors. SAE Technical Paper 1999-01-0640."), fp_p = fp_par_footnote),
  fpar(ftext("Freeman MD. Medicolegal causation analysis of a lumbar spine fracture following a low speed rear impact traffic crash. J Case Rep Prac 2015; 3(2): 23-9."), fp_p = fp_par_footnote),
  fpar(ftext("Croft AC, Haneline MT, Freeman MD. Low speed frontal crashes and low speed rear crashes: is there a differential risk for injury? Annu Proc Assoc Adv Automot Med. 2002;46:79-91."), fp_p = fp_par_footnote),
  fpar(ftext("Croft AC, Herring P, Freeman MD, Haneline MT: The neck injury criterion (NIC): future considerations. Accid Anal Prev 2002;34(2):247-55"), fp_p = fp_par_footnote),
  fpar(ftext("Nolet et al. Is acceleration a valid proxy for injury risk in minimal damage traffic crashes? A comparative review of volunteer, ADL and real-world studies. Environ Res Public Health 2021;18:2901; https://doi.org/10.3390/ijerph18062901."), fp_p = fp_par_footnote),
  fpar(ftext("https://orthoinfo.aaos.org/en/diseases--conditions/slap-tears/"), fp_p = fp_par_footnote),
  fpar(ftext("Waterman et al. Trends in the diagnosis of SLAP lesions in the US military. Knee Surg Sports Traumatol Arthrosc 2015;23:1453–9)."), fp_p = fp_par_footnote),
  fpar(ftext("Bartsch et al. Minor crashes and 'whiplash' in the United States. Ann Adv Automot Med 2008;52:117-28."), fp_p = fp_par_footnote),
  fpar(ftext("Adams M et al. Biomechanics of back pain. London, UK, Churchill Livingstone, 2012."), fp_p = fp_par_footnote),
  fpar(ftext("I was involved with the experimental protocols associated with the crash testing depicted in the proceding stills and can authenticate the results."), fp_p = fp_par_footnote),
  fpar(ftext("Human tolerance to impact conditions as related to motor vehicle design. SAE J885 2011"), fp_p = fp_par_footnote),
  fpar(ftext("Nationwide Inpatient Sample, Healthcare Utilization Project, Agency for Health Research and Quality, US Department of Health and Human Resources"), fp_p = fp_par_footnote),
  fpar(ftext("Nolet et al. Exposure to a Motor Vehicle Collision and the Risk of Future Neck Pain: A Systematic Review and Meta-Analysis. PM R. 2019 Apr 25. doi: 10.1002/pmrj.12173."), fp_p = fp_par_footnote),
  fpar(ftext("Nolet et al. Exposure to a motor vehicle collision and the risk of future back pain: A systematic review and meta-analysis. Accid Analysis Prev 2020: https://doi.org/10.1016/j.aap.2020.105546"), fp_p = fp_par_footnote),
  fpar(ftext("https://libguides.winona.edu/c.php?g=11614&p=61584"), fp_p = fp_par_footnote),
  fpar(ftext("Freeman MD, Croft AC, Rossignol AM, Weaver DS, Reiser M. A review and methodologic critique of the literature refuting whiplash syndrome. Spine 1999;24(1):86-98."), run_linebreak(), ftext("(NB this paper has been cited as an authority more than 220 times in the scientific literature – see https://scholar.google.com/scholar?hl=en&as_sdt=0%2C38&q=Freeman+MD+methodologic&btnG=)"), fp_p = fp_par_footnote),
  fpar(ftext("Nolet PS, Nordhoff L Kristman KL, Croft AC, Zeegers MP, Freeman MD. Is acceleration a valid proxy for injury risk in minimal damage traffic crashes? A comparative review of volunteer, ADL and real-world studies. Int J Environ Res Public Health 2021 2021;18:2901; https://doi.org/10.3390/ijerph18062901."), fp_p = fp_par_footnote),
  fpar(ftext("Freeman MD, Leith WM. Estimating the number of traffic crash-related cervical spine injuries in the United States; an analysis and comparison of national crash and hospital data. Accident Analysis and Prevention 2020: doi:https://doi.org/10.1016/j. aap.2020.105571."), fp_p = fp_par_footnote),
  fpar(ftext("Giuliano V, Giuliano C, Pinto F, Scaglione M. The use of flexion and extension MR in the evaluation of cervical spine trauma: initial experience in 100 trauma patients compared with 100 normal subjects. Emerg Radiol. 2002;9(5):249-53."), fp_p = fp_par_footnote),
  fpar(ftext("Freeman MD, Croft AC, Nicodemus CN, Centeno CJ, Welkins WL. Significant spinal injury resulting from low-level accelerations: A case series of roller coaster injuries. Arch Phys Med Rehab November 2005;86:2126-30."), fp_p = fp_par_footnote),
  fpar(ftext("Oppenheim JS, Spitzer DE, Segal DH. Nonvascular complications following spinal manipulation. Spine J. 2005;5(6):660-6."), fp_p = fp_par_footnote),
  fpar(ftext("Lutz JD, Smith RR, Jones HM. CT myelography of a fragment of a lumbar disk sequestered posterior to the thecal sac. AJNR Am J Neuroradiol. 1990;11(3):610-1."), fp_p = fp_par_footnote),
  fpar(ftext("Sadanand V, Kelly M, Varughese G, Fourney DR. Sudden quadriplegia after acute cervical disc herniation. Can J Neurol Sci. 2005;32(3):356-8."), fp_p = fp_par_footnote)
)

footnote_fpar <- fpar(
  "this paragraph contains a note",
  run_footnote(x = footnotes_blocklist[1], prop = fp_text_refnote),
  run_footnote(x = footnotes_blocklist[2], prop = fp_text_refnote),
  run_footnote(x = footnotes_blocklist[3], prop = fp_text_refnote),
  "."
)